MDScreen:
    name: "main"
    MDFloatLayout:
        md_bg_color: 41/255, 135/255, 168/255, 1

        MDTopAppBar:
            title: "Elevation 4"
            elevation: 4
            title: "[size=17][i][color=#f3d815]Atividade do Arthur[/size][/i][/color]"
            left_action_items: [["menu"]]
            right_action_items: [["close-octagon", lambda x: app.fechar()]]
            pos_hint: {"center_x": 0.5, "center_y": 0.95}



